import { routing, type Locale } from '@/i18n/routing';

/** Public URL of the site. Set NEXT_PUBLIC_SITE_URL in production (e.g. https://cuesetter.com). */
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';
export const SITE_NAME = 'Cuesetter';

/** Path of a page in a given locale: English has no prefix, other languages do. */
export function localePath(locale: Locale, path: string): string {
  const clean = path === '/' ? '' : path;
  return locale === routing.defaultLocale ? clean || '/' : `/${locale}${clean}`;
}

/** hreflang alternates and canonical URL for a page. */
export function alternates(locale: Locale, path: string) {
  return {
    canonical: localePath(locale, path),
    languages: {
      ...Object.fromEntries(routing.locales.map((l) => [l === 'no' ? 'nb' : l, localePath(l, path)])),
      'x-default': localePath(routing.defaultLocale, path),
    },
  };
}

/** Share image for a locale (generated by app/[locale]/opengraph-image.tsx). */
export function ogImages(locale: Locale) {
  return [{ url: localePath(locale, '/opengraph-image'), width: 1200, height: 630, alt: SITE_NAME }];
}
