import { routing, type Locale } from '@/i18n/routing';

/**
 * Public URL of the site, used for canonical links, hreflang, the sitemap and share images.
 * NEXT_PUBLIC_SITE_URL overrides it (e.g. for a preview domain).
 */
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? (process.env.NODE_ENV === 'production' ? 'https://cuesetter.com' : 'http://localhost:3000');
export const SITE_NAME = 'Cuesetter';

/** Path of a page in a given locale: English has no prefix, other languages do. */
export function localePath(locale: Locale, path: string): string {
  const clean = path === '/' ? '' : path;
  return locale === routing.defaultLocale ? clean || '/' : `/${locale}${clean}`;
}

/** hreflang alternates and canonical URL for a page. */
export function alternates(locale: Locale, path: string) {
  return {
    canonical: localePath(locale, path),
    languages: {
      ...Object.fromEntries(routing.locales.map((l) => [l === 'no' ? 'nb' : l, localePath(l, path)])),
      'x-default': localePath(routing.defaultLocale, path),
    },
  };
}

/** Share image for a locale (generated by app/[locale]/opengraph-image.tsx, always under /<locale>/). */
export function ogImages(locale: Locale) {
  return [{ url: `/${locale}/opengraph-image`, width: 1200, height: 630, alt: SITE_NAME }];
}
