import { routing, type Locale } from '@/i18n/routing';

/**
 * Public URL of the site, used for canonical links, hreflang, the sitemap and share images.
 * NEXT_PUBLIC_SITE_URL overrides it (e.g. for a preview domain).
 */
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? (process.env.NODE_ENV === 'production' ? 'https://cuesetter.com' : 'http://localhost:3000');
export const SITE_NAME = 'CueSetter';
/** Where users reach us (forwarded by Namecheap email forwarding). */
export const CONTACT_EMAIL = 'hello@cuesetter.com';

/**
 * IndexNow key (https://www.indexnow.org): proves to Bing and other search engines that pings for
 * cuesetter.com come from us. The same key is served at /<key>.txt (public/).
 */
export const INDEXNOW_KEY = '7dfcb76cf04eaf08144f631fba7bb9aa';

/**
 * Our profiles elsewhere (LinkedIn, YouTube …). Listed as sameAs in the Organization JSON-LD, so
 * search engines and AI connect them to CueSetter. Add a URL here when a profile is created.
 */
export const SOCIAL_PROFILES: string[] = ['https://www.instagram.com/cuesetter/', 'https://www.tiktok.com/@cuesetter'];

/**
 * The demo video on YouTube, shown on the front page and described as a VideoObject for Google.
 * Fill in when the video is published (docs/synlighet.md, step 2); null hides it.
 */
export const DEMO_VIDEO: { youtubeId: string; uploadDate: string; duration: string } | null = null;

/** BCP 47 language tag for a locale: Norwegian is written Bokmål (nb). */
export function languageTag(locale: Locale): string {
  return locale === 'no' ? 'nb' : locale;
}

/** Path of a page in a given locale: English has no prefix, other languages do. */
export function localePath(locale: Locale, path: string): string {
  const clean = path === '/' ? '' : path;
  return locale === routing.defaultLocale ? clean || '/' : `/${locale}${clean}`;
}

/** hreflang alternates and canonical URL for a page. */
export function alternates(locale: Locale, path: string) {
  return {
    canonical: localePath(locale, path),
    languages: {
      ...Object.fromEntries(routing.locales.map((l) => [languageTag(l), localePath(l, path)])),
      'x-default': localePath(routing.defaultLocale, path),
    },
  };
}

/** Share image for a locale (generated by app/[locale]/opengraph-image.tsx, always under /<locale>/). */
export function ogImages(locale: Locale) {
  return [{ url: `/${locale}/opengraph-image`, width: 1200, height: 630, alt: SITE_NAME }];
}
